networks:
  transcendence_network:
    driver: bridge

volumes:
  prometheus_data: {}
  postgres_data:

services:
  nginx:
    container_name: nginx
    image: nginx:1-alpine
    restart: unless-stopped
    ports:
      - 8080:80
    networks:
      - transcendence_network
  
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    networks:
      - transcendence_network

  django:
    build: ./django
    ports:
      - 8000:8000
    env_file:
      - ./.env

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev