networks:
  transcendence_network:
    driver: bridge

volumes:
  prometheus_data: {}

services:
  nginx:
    container_name: nginx
    image: nginx:1-alpine
    restart: unless-stopped
    ports:
      - 8080:80
    networks:
      - transcendence_network
  
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    networks:
      - transcendence_network
