networks:
  transcendence_network:
    driver: bridge

volumes:
  #prometheus_data: {}
  postgres_data:
  django:

services:
  nginx:
    container_name: nginx
    image: nginx:1-alpine
    restart: unless-stopped
    ports:
      - 8080:80
    networks:
      - transcendence_network
  
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    networks:
      - transcendence_network

  django:
    build: 
      context: ./django
      dockerfile: "Dockerfile"
      args:
        - SQL_HOST=${SQL_HOST}
        - SQL_PORT=${SQL_PORT}
    image: django
    pull_policy: never
    container_name: django
    volumes:
      - django:/usr/src/django/
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:15
    container_name: postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}