networks:
  transcendence_network:
    driver: bridge

volumes:
  prometheus_data: {}

services:
  nginx:
    container_name: nginx
    image: nginx:1-alpine
    restart: unless-stopped
    ports:
      - 8080:80
    networks:
      - transcendence_network
  
  node_exporter:
    container_name: node_exporter
    image: prom/node_exporter:v1.8.2
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - transcendence_network

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    networks:
      - transcendence_network
