networks:
  frontend_net:
    driver: bridge
  backend_net:
    driver: bridge
    # internal: true
    internal: false # in order to send 2FA
  monitoring_net:
    driver: bridge

volumes:
  vault_shared_data:
    driver: local
  vault_file:
    driver: local
  static_volume: {} # Added by Ben
  media_data: {} # docker volume for storing pictures
  logs_nginx: {}
  # logs_modsec: {}
  logs_django: {}
  redis_data: {}
  game_data: {}
  filebeat_registry: {}
  es_data:
    driver: local
  kibana_certs:
    driver: local
  prometheus_data: {}
  grafana_data: {}
  grafana_certs: {}
  html_volume: {}

services:
  # Security Layer
  vault:
    container_name: vault
    build:
      context: pong-game/security/vault
      dockerfile: Dockerfile
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    volumes:
      - vault_shared_data:/vault/shared_data
      - vault_file:/vault/file
    networks:
      - backend_net
    stop_signal: SIGTERM # DTIW
    healthcheck:
      test: ["CMD", "vault", "status", "-tls-skip-verify"]
      interval: 10s
      timeout: 5s
      retries: 3
    configs:
      - source: env_file
        target: /vault/.env
        mode: 0400

  # Frontend Layer
  ## [Theo] & [Alex]
  nginx:
    container_name: nginx
    build:
      context: pong-game/frontend/nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/app/static:ro
      - logs_nginx:/var/log/nginx
      - html_volume:/usr/share/nginx/html
      # - logs_modsec:/var/log/modsec
      - media_data:/app/media
    ports:
      - "8443:443"
      - "8080:80"
    networks:
      - frontend_net
      - backend_net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - django
    healthcheck:
      test: ["CMD", "curl", "-k", "https://localhost:443/health" ]
      interval: 2s
      timeout: 2s
      retries: 1
    restart: unless-stopped

  # Backend Layer
  ## [Ben] [Jean]
  django:
    container_name: django
    build:
      context: pong-game/backend
      dockerfile: Dockerfile
    image: django
    pull_policy: never
    volumes:
      - static_volume:/app/static
      - media_data:/home/app/pong-game/media
      - vault_shared_data:/vault/shared_data:ro
      - logs_django:/root/logs
    expose:
      - 8004
      - 8001
    depends_on:
      vault:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend_net
    environment:
      # connection to vault
      VAULT_ADDR: "https://vault:8200"
      VAULT_TOKEN_FILE: "/vault/shared_data/django_token.txt"
      VAULT_CACERT: "/vault/shared_data/certs/selfsigned.crt"
      # non-sensitive data
      DEBUG: "1"
      POSTGRES_PORT: "5434"
      LDB_UPDATE_TIMER: "1"
    restart: unless-stopped

  # Database Layer
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_PORT=5434
    command: postgres -p 5434
    volumes:
      - game_data:/var/lib/postgresql/data
      - media_data:/app/media
    networks:
      - backend_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost -p 5434 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - backend_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 5
    restart: unless-stopped

# Monitoring Layer
# Prometheus / Grafana Stack
  prometheus:
    container_name: prometheus
    build:
      context: pong-game/monitoring/prometheus
      dockerfile: Dockerfile
    image: prometheus
    # image: prom/prometheus:v2.45.0
    ports:
      - "9090:9090" #consider close in production
    volumes:
      - ./pong-game/monitoring/certs:/etc/prometheus/certs:ro
      - prometheus_data:/prometheus/data
    # environment:
    #   - PROM_ADMIN_USER=${PROM_ADMIN_USER}
    #   - PROM_ADMIN_PASS_HASH=${PROM_ADMIN_PASS_HASH}
    networks:
      - monitoring_net
      - backend_net
    depends_on:
      - node_exporter
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-k", "https://localhost:9090/-/healthy"]
      interval: 10s
      timeout: 3s
      retries: 3

  grafana:
    container_name: grafana
    build:
      context: pong-game/monitoring/grafana
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - GRAFANA_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GRAFANA_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_SERVER_PROTOCOL=https
      - GF_SERVER_CERT_FILE=/etc/grafana/certs/grafana.crt
      - GF_SERVER_CERT_KEY=/etc/grafana/certs/grafana.key
    volumes:
      - ./pong-game/monitoring/certs:/etc/grafana/certs:ro
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring_net
    depends_on:
      prometheus:
        condition: service_healthy
    restart: unless-stopped

  node_exporter:
    container_name: node_exporter
    build:
      context: pong-game/monitoring/node_exporter
      dockerfile: Dockerfile
    networks:
      - monitoring_net
    restart: unless-stopped

# ELK Stack
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_STACK_VERSION}
    environment:
      # Cluster configuration
      - node.name=es01
      - cluster.name=pong-game-logs
      - discovery.type=single-node
      - network.host=0.0.0.0
      # Basic settings
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      # Disk allocation setting
      - "cluster.routing.allocation.disk.threshold_enabled=true"
      - "cluster.routing.allocation.disk.watermark.low=85%"
      - "cluster.routing.allocation.disk.watermark.high=90%"
      - "cluster.routing.allocation.disk.watermark.flood_stage=95%"
      # Security settings (Admin user)
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      # Transport SSL settings
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=/usr/share/elasticsearch/config/certs/elastic-transport.key
      - xpack.security.transport.ssl.certificate=/usr/share/elasticsearch/config/certs/elastic-transport.crt
      - xpack.security.transport.ssl.certificate_authorities=/usr/share/elasticsearch/config/certs/ca.crt
      # HTTP SSL settings
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=/usr/share/elasticsearch/config/certs/elastic-http.key
      - xpack.security.http.ssl.certificate=/usr/share/elasticsearch/config/certs/elastic-http.crt
      - xpack.security.http.ssl.certificate_authorities=/usr/share/elasticsearch/config/certs/ca.crt
    volumes:
      - ./pong-game/monitoring/elk/certs:/usr/share/elasticsearch/config/certs:ro
      - es_data:/usr/share/elasticsearch/data
      - ./pong-game/monitoring/elk/elasticsearch/setup:/setup
    entrypoint: >
      sh -c '
        /usr/local/bin/docker-entrypoint.sh &
        ELASTIC_PID=$!
        sleep 15 &&
        /setup/init.sh &
        wait $ELASTIC_PID'
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    networks:
      - monitoring_net
    healthcheck:
      test: ["CMD-SHELL", "curl -k -s https://localhost:9200/_cat/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:${ELASTIC_STACK_VERSION}
    volumes:
      - ./pong-game/monitoring/elk/certs:/usr/share/kibana/config/certs:ro
      - ./pong-game/monitoring/elk/kibana/dashboards:/usr/share/kibana/dashboards
      - ./pong-game/monitoring/elk/kibana/setup:/usr/share/kibana/setup
    ports:
      - "5601:5601" # Only external access point for ELK
    environment:
      # Elasticsearch connection
      - ELASTICSEARCH_HOSTS=https://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      # Server settings
      - SERVER_HOST=0.0.0.0
      - SERVER_NAME=kibana
      # Security settings (Internal Security Settings)
      - XPACK_SECURITY_ENABLED=true
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=${ELASTIC_PASSWORD}
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=/usr/share/kibana/config/certs/ca.crt
      - ELASTICSEARCH_SSL_VERIFICATIONMODE=certificate
      # Performance settings
      - ELASTICSEARCH_REQUESTTIMEOUT=90000  # Added timeout
      - OPTIMIZATION_PROFILING=false
      # Other settings
      - TELEMETRY_ENABLED=false
      # For External HTTPS access settings
      - SERVER_SSL_ENABLED=true
      - SERVER_SSL_CERTIFICATE=/usr/share/kibana/config/certs/kibana.crt
      - SERVER_SSL_KEY=/usr/share/kibana/config/certs/kibana.key
      - SERVER_SSL_REDIRECT=true
    networks:
      - monitoring_net
    depends_on:
      elasticsearch:
        condition: service_healthy
    entrypoint: >
      sh -c '
        /usr/share/kibana/setup/import-dashboards.sh &
        /usr/local/bin/kibana-docker'
    restart: unless-stopped

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:${ELASTIC_STACK_VERSION}
    volumes:
      - ./pong-game/monitoring/elk/logstash/docker-entrypoint.sh:/entrypoint.sh:ro
      - ./pong-game/monitoring/elk/certs:/usr/share/logstash/config/certs:ro
      - ./pong-game/monitoring/elk/logstash/config/logstash.yml:/tmp/logstash.yml:ro
      - ./pong-game/monitoring/elk/logstash/pipeline:/usr/share/logstash/pipeline:ro
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    environment:
      - LS_JAVA_OPTS=-Xmx256m -Xms256m
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      # SSL / TLS setting
      - XPACK_MONITORING_ELASTICSEARCH_HOSTS=https://elasticsearch:9200
      - XPACK_MONITORING_ELASTICSEARCH_USERNAME=${ELASTIC_USER}
      - XPACK_MONITORING_ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      - XPACK_MONITROING_ELASTICSEARCH_SSL_CERTIFICATE_AUTHORITY=/usr/share/logstash/config/certs/ca.crt
    networks:
      - monitoring_net
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9600"]
      interval: 10s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:${ELASTIC_STACK_VERSION}
    user: root  # Required to read logs
    volumes:
      - ./pong-game/monitoring/elk/certs:/usr/share/filebeat/certs:ro
      - ./pong-game/monitoring/elk/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      # Mount all log directories
      - logs_nginx:/var/log/nginx
      # - logs_modsec:/var/log/modsec
      - logs_django:/var/log/django
      - filebeat_registry:/usr/share/filebeat/data
    environment:
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    entrypoint: >
      sh -c '
      chmod go-w /usr/share/filebeat/filebeat.yml &&
      filebeat -e --strict.perms=false'
    networks:
      - monitoring_net
      - frontend_net
      - backend_net
    depends_on:
      logstash:
        condition: service_healthy

configs:
  env_file:
    file: .env
