{
 "title": "Django Metrics Dashboard",
 "description": "Demo dashboards from Django metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Django Request Latency",
   "type": "timeseries",
   "description": "Monitor Django http request latency",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "django_http_requests_latency_including_middlewares_seconds_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Request top 5",
   "type": "bargauge",
   "description": "Top 5 API request types ",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(view) (django_http_requests_total_by_view_transport_method_total{view!=\"django-metrics\"})",
     "legendFormat": "{{view}}"
    }
   ]
  },
  {
   "title": "Response breakdown by view",
   "type": "piechart",
   "description": "API response breakdown by vew",
   "gridPos": { "h": 9, "w": 7, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(view) (django_http_responses_total_by_status_view_method_total{view!=\"django-metrics\"})",
     "legendFormat": "{{view}}"
    }
   ]
  }
 ]
}