global:
  scrape_internal: 15s
  evaluation_interval: 15s

rule_files:
  - "alert.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth_service:8001']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user_service:8002']

  - job_name: 'game-service'
    static_configs:
      - targets: ['game_service:8004']