apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: https://prometheus:9090
    jsonData:
      tlsAuth: false
      tlsSkipVerify: true
      timeInterval: "15s"
    isDefault: true
    editable: true