filebeat.inputs:
# Nginx Logs
- type: filestream
  id: nginx-access-logs
  enabled: true
  paths:
    - /var/log/nginx/access.log
  json.keys_under_root: true
  json.add_error_key: true
  fields:
    type: "nginx"
    source: "access"

- type: filestream
  id: nginx-error-logs
  enabled: true
  paths:
    - /var/log/nginx/error.log
  fields:
    type: "nginx"
    source: "error"

## Other logs collection templates for future expansion
# # Application Services Logs
# - type: filestream
#   id: auth-service-logs
#   enabled: true
#   paths:
#     - /var/log/auth/*.log
#   fields:
#     type: application
#     service: auth
#     category: security

# - type: filestream
#   id: user-service-logs
#   enabled: true
#   paths:
#     - /var/log/user/*.log
#   fields:
#     type: application
#     service: user
#     category: user

# - type: filestream
#   id: game-service-logs
#   enabled: true
#   paths:
#     - /var/log/game/*.log
#   fields:
#     type: application
#     service: game
#     category: gameplay

output.logstash:
  hosts: ["logstash:5044"]

# # Debug by bypassing Logstash
# output.elasticsearch:
#   hosts: ["elasticsearch:9200"]
#   indices:
#     - index: "nginx-logs-%{+yyyy.MM.dd}"

# setup.template.name: "nginx-logs"
# setup.template.pattern: "nginx-logs-*"
# setup.ilm.enabled: false

logging.json: true
logging.metrics.enabled: false

logging.level: debug