filebeat.inputs:
# Nginx Logs
- type: filestream
  id: nginx-access-logs
  enabled: true
  paths:
    - /var/log/nginx/access.log
  json.keys_under_root: true
  json.add_error_key: true
  fields:
    type: "nginx"
    source: "access"

- type: filestream
  id: nginx-error-logs
  enabled: true
  paths:
    - /var/log/nginx/error.log
  fields:
    type: "nginx"
    source: "error"

- type: filestream
  id: modsecurity-audit-logs
  enabled: true
  paths:
    - /var/log/modsec/audit.log
  fields:
    type: "waf"
    source: "audit"
  multiline:
    pattern: '^--[a-fA-F0-9]{8}-[A-Z]--$'
    negate: true
    match: after

- type: filestream
  id: modsecurity-debug-logs
  enabled: true
  paths:
    - /var/log/modsec/debug.log
  fields:
    type: "waf"
    source: "debug"

## Other logs collection templates for future expansion
# # Application Services Logs
# - type: filestream
#   id: auth-service-logs
#   enabled: true
#   paths:
#     - /var/log/auth/*.log
#   fields:
#     type: application
#     service: auth
#     category: security

# - type: filestream
#   id: user-service-logs
#   enabled: true
#   paths:
#     - /var/log/user/*.log
#   fields:
#     type: application
#     service: user
#     category: user

# - type: filestream
#   id: game-service-logs
#   enabled: true
#   paths:
#     - /var/log/game/*.log
#   fields:
#     type: application
#     service: game
#     category: gameplay

output.logstash:
  hosts: ["logstash:5044"]

logging:
  level: info
  to_files: true
  files:
    path: /var/log/filebeat
    name: filebeat
    keepfiles: 7
    permissions: 0644

setup.ilm.enabled: false
setup.template.enabled: false