export const translations = {
	en: {
		home: "Home",
		game: "Game",
		leaderboard: "Leaderboard",
		settings: "Settings",
		about: "About",
		user: "User",
		colorMode: "Color Mode",
		lightMode: "Light",
		darkMode: "Dark",
		colorblindMode: "Colorblind",
		error404Title: "404",
		error404Message: "Error 404: Page not found",
		fontSize: "Font Size",
		smallFont: "Small",
		mediumFont: "Medium",
		largeFont: "Large",
		language: "Language",
		login: "Log in",
		profile: "Profile",
		logout: "Log out",
		loginTitle: "Login",
		username: "Username",
		password: "Password",
		loginButton: "Log In",
		emptyField: "Please fill out this field.",
		noAccount: "Don’t have an account?",
		createAccountLink: "Create one here",
		createAccountTitle: "Create Account",
		newUsername: "Username",
		newPassword: "Password",
		confirmPassword: "Confirm Password",
		passwordMismatch: "Passwords do not match.",
		profilePicture: "Profile Picture",
		profilePictureHint: "Only .jpg and .png files are allowed.",
		invalidFormat: "Invalid file type. Only .jpg and .png are allowed.",
		createAccountButton: "Create Account",
		newLogin: "Login",
		newMail: "Mail Address",
	},
	fr: {
		home: "Accueil",
		game: "Jeu",
		leaderboard: "Classement",
		settings: "Paramètres",
		about: "À propos",
		user: "Utilisateur",
		colorMode: "Choix des couleurs",
		lightMode: "Clair",
		darkMode: "Sombre",
		colorblindMode: "Daltonien",
		error404Title: "404",
		error404Message: "Erreur 404 : Page introuvable",
		fontSize: "Taille de la police",
		smallFont: "Petite",
		mediumFont: "Moyenne",
		largeFont: "Grande",
		language: "Langue",
		login: "Se connecter",
		profile: "Profil",
		logout: "Se déconnecter",
		loginTitle: "Connexion",
		username: "Nom d'utilisateur",
		password: "Mot de passe",
		loginButton: "Se connecter",
		emptyField: "Veuillez remplir ce champ.",
		noAccount: "Pas de compte ?",
		createAccountLink: "Créez-en un ici",
		createAccountTitle: "Créer un compte",
		newUsername: "Nom d'utilisateur",
		newPassword: "Mot de passe",
		confirmPassword: "Confirmer le mot de passe",
		passwordMismatch: "Les mots de passe ne correspondent pas.",
		profilePicture: "Photo de profil",
		profilePictureHint: "Seuls les fichiers .jpg et .png sont autorisés.",
		invalidFormat: "Type de fichier invalide. Seuls les formats .jpg et .png sont autorisés.",
		createAccountButton: "Créer le compte",
		newLogin: "Identifiant",
		newMail: "Adresse Mail",
	},
	pt: {
		home: "Início",
		game: "Jogo",
		leaderboard: "Classificação",
		settings: "Configurações",
		about: "Sobre",
		user: "Usuário",
		colorMode: "Modo de Cor",
		lightMode: "Claro",
		darkMode: "Escuro",
		colorblindMode: "Daltônico",
		error404Title: "404",
		error404Message: "Erro 404: Página não encontrada",
		fontSize: "Tamanho da fonte",
		smallFont: "Pequena",
		mediumFont: "Média",
		largeFont: "Grande",
		language: "Linguagem",
		login: "Conecte-se",
		profile: "Perfil",
		logout: "Sair",
		username: "Nome de usuário",
		password: "Senha",
		loginButton: "Login",
		emptyField: "Por favor preencha este campo.",
		noAccount: "Sem conta?",
		createAccountLink: "Crie um aqui",
		createAccountTitle: "Criar uma conta",
		newUsername: "Nome de usuário",
		newPassword: "Senha",
		confirmPassword: "Confirmar senha",
		passwordMismatch: "As senhas não coincidem.",
		profilePicture: "Foto do perfil",
		profilePictureHint: "Somente arquivos .jpg e .png são permitidos.",
		invalidFormat: "Tipo de arquivo inválido. Somente .jpg e .png são permitidos.",
		createAccountButton: "Criar conta",
		newLogin: "Identificador",
		newMail: "Endereço De Email",
	},
};
