export const translations = {
	en: {
		//Login_html
		loginInput: "Login",
		chooseLogin: "Choose a Login",
		alias: "Alias",
		chooseAlias: "Choose an alias",
		mail: "Mail",
		enterMail: "Enter your mail",
		password: "Password",
		choosePassword: "Choose a password",
		confirmPassword: "Confirm Password",
		reenterPassword: "Re-enter your password",
		registerButton: "Register",
		alreadyAccount: "Already have an account?",
		loginLink: "Login here",
		//error and success messages for Login_html
		registerSucceeded: "Success! User profile has been created, you can now log in.",
		badLanguage: "contains bad language",
		loginTaken: "User with this login already exists",
		aliasTaken: "User with this alias already exists",
		invalidMail: "Enter a valid email address",
		emailTaken: "User with this email already exists",
		registerFailed: "Register failed, please try again later.",
		internalError: "An error occurred. Please try again later.",
		invalidFormat: "Invalid file type. Only .jpg and .png are allowed.",
		emptyField: "Please fill out this field.",
		//login_login
		loginTitle: "Login",
		enterLogin: "Enter your Login",
		enterPassword: "Enter your password",
		noAccount: "Don’t have an account?",
		registerLink: "Create one here",
		twoFactorCode: "2FA Code",
		enter2FA: "Enter 2FA Code",
		check2FA: "Verify 2FA",
		//login_login error and success management
		invalidCredential:"Login failed: Invalid Login or Password",
		enter2FA: "Enter the 2FA code sent to your email.",
		loginFailed : "Login failed. Please try again.",
		twoFactorFailed: "2FA verification failed.",
		//Navbar
		home: "Home",
		game: "Game",
		leaderboard: "Leaderboard",
		settings: "Settings",
		about: "About",
		user: "User",
		logout: "Log out",
		personalData: "My information",
		//Personnal Information 
		confirm: "Confirm",
		cancel: "Cancel",
		//Personnal info Alias change
		aliasChanged: "Success, alias has been changed.",
		IncorrectValue: "Error, please enter a correct value.",
		//Personnal info Mail change
		mailChanged: "Success, email has been changed.",
		oldPassword: "Old password",
		confirmNewPassword: "Confirm new password",
		close: "Close",
		newPassword: "New password",
		passwordMismatch: "Passwords do not match.",
		passwordChanged: "Success, password has been changed.",
		passwordRule: "Your password must blablabla update this pls", //to update
		profilePicture: "Profile Picture",
		profilePictureHint: "Only .jpg and .png files are allowed.",
		errorUploading: "Error uploading profile picture",
		//profile
		searchByUsername: "Search by username",
		profileTitle: "Search Profile",
		searchButton: "Search",
		userNotFound: "User not found.",
		status: "Status",
		rank: "Rank",
		unranked: "Unranked",
		mmr: "MMR",
		winRate: "Win Rate",
		wins: "Wins",
		losses: "Losses",
		matchHistory: "Match History:",
		noMatchHistory: "No match history found.",
		win: "Win",
		loss: "Loss",
		w: "W",
		l: "L",
		online: "Online",
		offline: "Offline",
		ingame: "In Game",
		friends: "Friends",
		sendMessage: "Send Message",
		requestDuel: "Send Duel Request",
		colorMode: "Color Mode",
		lightMode: "Light",
		darkMode: "Dark",
		colorblindMode: "Colorblind",
		error404Title: "404",
		error404Message: "Error 404: Page not found",
		fontSize: "Font Size",
		smallFont: "Small",
		mediumFont: "Medium",
		largeFont: "Large",
		language: "Language",
		login: "Log in",
		profile: "Profile",
		username: "Username",
		password: "Password",
		loginButton: "Log In",
		registerTitle: "Register",
		newUsername: "Username",
		newAlias: "Alias",
		newMail: "Mail Address",
		addFriend: "Add to friend list",
		addNewFriend: "Add a new friend",
		enterUsername: "Enter username",
		removeFriend: "Remove from friend list",
		friendList: "Friend list",
		validationRemovalFirst: "Are you sure you want to remove",
		validationRemovalSecond: "from your friend list",
		friendAndBlockList: "Friends & Block List",
		blockList: "Blocked List",
		blockUser: "Block User",
		addBlock: "Block a new user",
		unblock: "Unblock",
		prompAddBlock: "Enter username to block",
		validationUnblockFirst: "Are you sure you want to unblock",
		validationUnblockSecond: "",
		promptAddFriend: "Enter the username of the friend you want to add",
		alreadyFriend: "is already your friend",
		alreadyBlock: "is already blocked",
		notFound: "not found",
		lonelyTest: "... I mean come on you can't be that lonely... you want a hug ?",
		chat: "Chat",
		okSasuke: "... Just how much do you hate yourself ? but no we can't let you do that...",
		solo: "Single Player",
		multi: "Multiplayer",
		easy: "Easy",
		medium: "Medium",
		hard: "Hard",
		back: "↵ Go back",
		local: "Local",
		duel: "Versus",
		tournament: "Tournament",
		quickMatch: "Quick Match",
		noFriends: "You have no friends.",
		noFriendRequests: "You have no pending friend requests.",
		noSentRequests: "You have not sent any friend requests.",
		noBlocks: "You have no blocked users.",
		friendRequests: "Friend Requests",
		sentRequests: "Sent Requests",
		addBlock: "Add to Block List",
		addFriendButton: "Add Friend",
		removeFriend: "Remove Friend",
		sendMessage: "Send Message",
		requestDuel: "Send Duel Request",
		accept: "Accept",
		cancel: "Cancel",
		block: "Block",
		friendRequestSent: "Friend request sent",
		blockedByUser: "is blocking you",
		blockingUser: "you are blocking",
		alreadySent: "Friend request was already sent.",
		welcome:"Welcome",
		currentStats:"Your current stats: ",
		date: "date",
		opponent: "opponent",
		finalScore: "final score",
		privateMessages: "Private messages",
		createOrJoinRoom: "Create or join room",
		chatRooms: "Chat rooms",
		enterRoomName: "Enter room name",
		privateMessagesWith: "Private messages with",
		changePassword: "Change Password",
	},
	fr: {
		confirm: "Confirmer",
		cancel: "Annuler",
		close: "Fermer",
		home: "Accueil",
		game: "Jeu",
		leaderboard: "Classement",
		settings: "Paramètres",
		about: "À propos",
		user: "Utilisateur",
		colorMode: "Choix des couleurs",
		lightMode: "Clair",
		darkMode: "Sombre",
		colorblindMode: "Daltonien",
		error404Title: "404",
		error404Message: "Erreur 404 : Page introuvable",
		fontSize: "Taille de la police",
		smallFont: "Petite",
		mediumFont: "Moyenne",
		largeFont: "Grande",
		language: "Langue",
		login: "Se connecter",
		profile: "Profil",
		personalData: "Mes informations",
		logout: "Se déconnecter",
		loginTitle: "Connexion",
		username: "Nom d'utilisateur",
		password: "Mot de passe",
		loginButton: "Se connecter",
		emptyField: "Veuillez remplir ce champ.",
		alreadyAccount: "Vous avez deja un compte ?",
		loginLink: "Connectez-vous",
		noAccount: "Pas de compte ?",
		registerLink: "Créez-en un ici",
		registerTitle: "Créer un compte",
		newUsername: "Nom d'utilisateur",
		profilePicture: "Photo de profil",
		newPassword: "Nouveau mot de passe",
		confirmPassword: "Confirmer le mot de passe",
		passwordMismatch: "Les mots de passe ne correspondent pas.",
		profilePictureHint: "Seuls les fichiers .jpg et .png sont autorisés.",
		invalidFormat: "Type de fichier invalide. Seuls les formats .jpg et .png sont autorisés.",
		registerButton: "Créer le compte",
		newAlias: "Alias",
		newMail: "Adresse Mail",
		profileTitle: "Rechercher un profil",
		searchButton: "Rechercher",
		userNotFound: "Utilisateur non trouvé.",
		status: "Statut",
		rank: "Rang",
		mmr: "MMR",
		winRate: "Taux de victoire",
		wins: "Victoires",
		losses: "Défaites",
		matchHistory: "Historique des matchs",
		noMatchHistory: "Aucune donnée trouvée dans l'historique des matchs.",
		win: "Victoire",
		w: "V",
		l: "D",
		loss: "Défaite",
		online: "En ligne",
		offline: "Hors ligne",
		ingame: "En jeu",
		friends: "Amis",
		sendMessage: "Envoyer un message",
		requestDuel: "Envoyer une demande de Duel",
		addFriend: "Ajouter à la liste d'amis",
		addNewFriend: "Ajouter un nouvel ami",
		removeFriend: "Supprimer de la liste d'amis",
		friendList: "Liste d'amis",
		friendAndBlockList: "Liste d'Amis & Bloqués",
		blockList: "Liste des Bloqués",
		blockUser: "Bloquer l'utilisateur",
		unblock: "Débloquer",
		addBlock: "Bloquer un nouvel utilisateur",
		prompAddBLock: "Entrez le nom d'utilisateur à bloquer",
		validationUnblockFirst: "Êtes-vous sûr de vouloir débloquer",
		validationUnblockSecond: "",
		validationRemovalFirst: "Êtes-vous sûr de vouloir supprimer",
		validationRemovalSecond: "de votre liste d'amis",
		promptAddFriend: "Entrez le nom d'utilisateur de l'ami que vous souhaitez ajouter",
		alreadyFriend: "est déjà votre ami",
		alreadyBlock: "est déjà bloqué",
		notFound: "n'a ​​pas été trouvé",
		lonelyTest: "... Je veux dire, allez, tu ne peux pas être si seul... tu veux un câlin ?",
		okSasuke: "... À quel point te détestes-tu ? mais non, nous ne pouvons pas te laisser faire ça...",
		chat: "Chat",
		solo: "Joueur seul",
		multi: "Multijoueur",
		easy: "Facile",
		medium: "Moyen",
		hard: "Difficile",
		back: "↵ Retour",
		local: "Local",
		duel: "Duel",
		tournament: "Tournoi",
		quickMatch: "Match rapide",
		enterUsername: "Entrez le nom d'utilisateur",
		prompAddBlock: "Entrez le nom d'utilisateur à bloquer",
		okSasuke: "... À quel point te détestes-tu ? mais non, nous ne pouvons pas te laisser faire ça...",
		noFriends: "Vous n'avez pas d'amis.",
		noFriendRequests: "Vous n'avez pas de demandes d'ami en attente.",
		noSentRequests: "Vous n'avez pas envoyé de demandes d'ami.",
		noBlocks: "Vous n'avez aucun utilisateur bloqué.",
		friendRequests: "Demandes d'ami",
		sentRequests: "Demandes envoyées",
		addBlock: "Ajouter à la liste des bloqués",
		addFriendButton: "Ajouter un ami",
		removeFriend: "Supprimer l'ami",
		sendMessage: "Envoyer un message",
		requestDuel: "Envoyer une demande de duel",
		accept: "Accepter",
		block: "Bloquer",
		friendRequestSent: "Demande d'ami envoyée",
		blockedByUser: "vous bloque",
		blockingUser: "vous bloquez",
		alreadySent: "La demande d'ami a déjà été envoyée.",
		welcome: "Bienvenue",
		currentStats: "Vos statistiques actuelles : ",
		date: "date",
		opponent: "adversaire",
		finalScore: "score final",
		privateMessages: "Messages privés",
		searchByUsername: "Rechercher par nom d'utilisateur",
		createOrJoinRoom: "Créer ou rejoindre une salle",
		chatRooms: "Salons de discussion",
		enterRoomName: "Entrez le nom de la salle",
		privateMessagesWith: "Messages privés avec",
		changePassword: "Changer le mot de passe",
		oldPassword: "Ancien mot de passe",
		confirmNewPassword: "Confirmer le nouveau mot de passe",
	},
	pt: {
		confirm: "Confirmar",
		cancel: "Cancelar",
		close: "Fechar",
		home: "Início",
		game: "Jogo",
		leaderboard: "Classificação",
		settings: "Configurações",
		about: "Sobre",
		user: "Usuário",
		colorMode: "Modo de Cor",
		lightMode: "Claro",
		darkMode: "Escuro",
		colorblindMode: "Daltônico",
		error404Title: "404",
		error404Message: "Erro 404: Página não encontrada",
		fontSize: "Tamanho da fonte",
		smallFont: "Pequena",
		mediumFont: "Média",
		largeFont: "Grande",
		language: "Linguagem",
		login: "Conecte-se",
		profile: "Perfil",
		personalData: "Minhas informações",
		logout: "Sair",
		loginTitle: "Conexão",
		username: "Nome de usuário",
		password: "Senha",
		loginButton: "Conectar-se",
		emptyField: "Por favor preencha este campo.",
		alreadyAccount: "Já tem uma conta?",
		loginLink: "Conecte-se",
		noAccount: "Sem conta?",
		registerLink: "Crie um aqui",
		registerTitle: "Criar uma conta",
		newUsername: "Nome de usuário",
		newPassword: "Nova senha",
		confirmPassword: "Confirmar senha",
		passwordMismatch: "As senhas não coincidem.",
		profilePicture: "Foto do perfil",
		profilePictureHint: "Somente arquivos .jpg e .png são permitidos.",
		invalidFormat: "Tipo de arquivo inválido. Somente .jpg e .png são permitidos.",
		registerButton: "Criar conta",
		newAlias: "Alias",
		newMail: "Endereço De Email",
		profileTitle: "Procurar Perfil",
		searchButton: "Pesquisar",
		userNotFound: "Usuário não encontrado.",
		status: "Status",
		rank: "Posição",
		mmr: "MMR",
		winRate: "Taxa de vitória",
		wins: "Vitórias",
		losses: "Derrotas",
		matchHistory: "Histórico de Partidas",
		noMatchHistory: "Nenhum dado encontrado no histórico de partidas.",
		win: "Vitória",
		w: "V",
		l: "D",
		loss: "Derrota",
		online: "Online",
		offline: "Offline",
		friends: "Amigos",
		ingame: "No jogo",
		sendMessage: "Enviar mensagem",
		requestDuel: "Enviado uma demanda de duelo",
		addFriend: "Adicionar à lista de amigos",
		addNewFriend: "adicione um novo amigo",
		removeFriend: "Remover da lista de amigos",
		friendList: "lista de amigos",
		friendAndBlockList: "Lista de Amigos e Bloqueados",
        blockList: "Lista de Bloqueados",
        blockUser: "Bloquear Usuário",
        unblock: "Desbloquear",
		addBlock: "Bloquear um novo Usuário",
        prompAddBLock: "Digite o nome de usuário para bloquear",
        validationUnblockFirst: "Tem certeza de que deseja desbloquear",
        validationUnblockSecond: "?",
		validationRemovalFirst: "Tem certeza de que deseja remover",
		validationRemovalSecond: "da sua lista de amigos",
		promptAddFriend: "Digite o nome de usuário do amigo que você deseja adicionar",
		alreadyFriend: "já é seu amigo",
		alreadyBlock: "já está bloqueado",
		notFound: "não encontrado",
		lonelyTest: "...Quer dizer, vamos lá, você não pode ficar tão sozinho... quer um abraço?",
		okSasuke: "... O quanto você se odeia? Mas não, não podemos deixar você fazer isso...",
		chat: "Chat",
		solo: "Jogador único",
		multi: "Multijogador",
		easy: "Fácil",
		medium: "Médio",
		hard: "Difícil",
		back: "↵ Voltar",
		local: "Local",
		duel: "Duelo",
		tournament: "Torneio",
		quickMatch: "Partida rápida",
		enterUsername: "Digite o nome de usuário",
		prompAddBlock: "Digite o nome de usuário para bloquear",
		okSasuke: "... Quanto você se odeia? Mas não, não podemos deixar você fazer isso...",
		noFriends: "Você não tem amigos.",
		noFriendRequests: "Você não tem pedidos de amizade pendentes.",
		noSentRequests: "Você não enviou nenhum pedido de amizade.",
		noBlocks: "Você não tem usuários bloqueados.",
		friendRequests: "Pedidos de Amizade",
		sentRequests: "Pedidos Enviados",
		addBlock: "Adicionar à Lista de Bloqueados",
		addFriendButton: "Adicionar Amigo",
		removeFriend: "Remover Amigo",
		sendMessage: "Enviar Mensagem",
		requestDuel: "Enviar Pedido de Duelo",
		accept: "Aceitar",
		block: "Bloquear",
		friendRequestSent: "Pedido de amizade enviado",
		blockedByUser: "está te bloqueando",
		blockingUser: "você está bloqueando",
		alreadySent: "O pedido de amizade já foi enviado.",
		welcome: "Bem-vindo",
		currentStats: "Suas estatísticas atuais: ",
		date: "data",
		opponent: "oponente",
		finalScore: "placar final",
		privateMessages: "Mensagens privadas",
		searchByUsername: "Pesquisar por nome de usuário",
		createOrJoinRoom: "Criar ou entrar em uma sala",
		chatRooms: "Salas de bate-papo",
		enterRoomName: "Insira o nome da sala",
		privateMessagesWith: "Mensagens privadas com",
		changePassword: "Alterar a senha",
		oldPassword: "Senha antiga",
		confirmNewPassword: "Confirmar a nova senha",
	},
};

