export const translations = {
	en: {
		//Login_html
		loginInput: "Login",
		registerTitle: "Register",
		chooseLogin: "Choose a Login",
		alias: "Alias",
		chooseAlias: "Choose an alias",
		mail: "Mail",
		enterMail: "Enter your mail",
		password: "Password",
		choosePassword: "Choose a password",
		confirmPassword: "Confirm Password",
		reenterPassword: "Re-enter your password",
		registerButton: "Register",
		alreadyAccount: "Already have an account?",
		loginLink: "Login here",
		//error and success messages for Login_html
		registerSucceeded: "Success! User profile has been created, you can now log in.",
		badLanguage: "contains bad language",
		loginTaken: "User with this login already exists",
		aliasTaken: "User with this alias already exists",
		invalidMail: "Enter a valid email address",
		emailTaken: "User with this email already exists",
		registerFailed: "Register failed, please try again later.",
		internalError: "An error occurred. Please try again later.",
		invalidFormat: "Invalid file type. Only .jpg and .png are allowed.",
		emptyField: "Please fill out this field.",
		//login_register
		pwWrongSize: "Password must be longer than 12 characters",
		pwMissingUpper: "Password must contain at least one uppercase letter",
		pwMissingLower: "Password must contain at least one lowercase letter",
		pwMissingNumber: "Password must contain at least one number",
		pwMissingSpecial: "Password must contain at least one special character",
		tooLong: "alias length cannot exceed 10 characters",
		//login_login
		loginTitle: "Login",
		login: "Log in",
		enterLogin: "Enter your Login",
		enterPassword: "Enter your password",
		noAccount: "Don’t have an account?",
		registerLink: "Create one here",
		twoFactorCode: "2FA Code",
		enter2FA: "Enter 2FA Code",
		check2FA: "Verify 2FA",
		//login_login error and success management
		invalidCredential:"Login failed: Invalid Login or Password",
		enter2FA: "Enter the 2FA code sent to your email.",
		loginFailed : "Login failed. Please try again.",
		twoFactorFailed: "2FA verification failed.",
		//Navbar
		home: "Home",
		game: "Game",
		leaderboard: "Leaderboard",
		settings: "Settings",
		profile: "Profile",
		about: "About",
		user: "User",
		logout: "Log out",
		personnalData: "My information",
		//Personnal Information
		confirm: "Confirm",
		cancel: "Cancel",
		language: "Language",
		//Personnal info Alias change
		aliasChanged: "Success, alias has been changed.",
		IncorrectValue: "Error, please enter a correct value.",
		//Personnal info Mail change
		mailChanged: "Success, email has been changed.",
		oldPassword: "Old password",
		confirmNewPassword: "Confirm new password",
		close: "Close",
		newPassword: "New password",
		changePassword: "Change Password",
		passwordMismatch: "Passwords do not match.",
		passwordChanged: "Success, password has been changed.",
		passwordRule: "Your password must blablabla update this pls", //to update
		profilePicture: "Profile Picture",
		profilePictureHint: "Only .jpg and .png files are allowed.",
		errorUploading: "Error uploading profile picture",
		//profile
		searchByUsername: "Search by username",
		profileTitle: "Search Profile",
		searchButton: "Search",
		userNotFound: "User not found.",
		status: "Status",
		rank: "Rank",
		unranked: "Unranked",
		mmr: "MMR",
		winRate: "Win Rate",
		wins: "Wins",
		losses: "Losses",
		matchHistory: "Match History:",
		noMatchHistory: "No match history found.",
		win: "Win",
		loss: "Loss",
		w: "W",
		l: "L",
		online: "Online",
		offline: "Offline",
		ingame: "In Game",
		friends: "Friends",
		sendMessage: "Send Message",
		requestDuel: "Send Duel Request",
		addFriend: "Add to friend list",
		accept: "Accept",
		cancel: "Cancel",
		block: "Block",
		removeFriend: "Remove from friend list",
		unblock: "Unblock",
		ban: "ban",
		unban: "unban",
		//leaderboard
		noData: "No data Available",
		//home
		welcome:"Welcome",
		currentStats:"Your current stats: ",
		date: "date",
		opponent: "opponent",
		//FriendList
		friendList: "Friend list",
		noFriends: "You have no friends.",
		noFriendRequests: "You have no pending friend requests.",
		noSentRequests: "You have not sent any friend requests.",
		noBlocks: "You have no blocked users.",
		blockList: "Blocked List",
		blockUser: "Block User",
		addBlock: "Block a new user",
		addNewFriend: "Add friend",
		enterUsername: "Enter username",
		friendRequests: "Friend Requests",
		sentRequests: "Sent Requests",
		addBlock: "Block user",
		addFriendButton: "Add Friend",
		removeFriend: "Remove Friend",
		promptAddBlock: "Enter username to block",
		promptAddFriend: "Enter the username of the friend you want to add",
		//manage_social
		validationRemovalFirst: "Are you sure you want to remove",
		validationRemovalSecond: "from your friend list",
		friendRequestSent: "Friend request sent",
		validationUnblockFirst: "Are you sure you want to unblock",
		validationUnblockSecond: "",
		alreadyFriend: "is already your friend",
		alreadyBlock: "is already blocked",
		notFound: "not found",
		lonelyTest: "... I mean come on you can't be that lonely... you want a hug ?",
		chat: "Chat",
		okSasuke: "... Just how much do you hate yourself ? but no we can't let you do that...",
		userblocked: "has been blocked",
		colorMode: "Color Mode",
		blockedByUser: "is blocking you",
		blockingUser: "You have blocked",
		alreadySent: "Friend request was already sent.",
		//404
		error404Title: "404",
		error404Message: "Error 404: Page not found",
		//chat
		chatRoomCreationFailed: "Failed to create room",
		emptyChatRoomName: "Room name is empty",
		privateMessages: "Private messages",
		createOrJoinRoom: "Create or join room",
		errorLoadingMessage: "Error loading messages.",
		hasInvitedYou: "has invited you to play",
		youInvited: "You sent an invite to play",
		chatRooms: "Chat rooms",
		privateMessagesWith: "Private messages with",
		enterRoomName: "Enter room name",
		tournamentRooms: "Tournament rooms",
		backButton: "↵ Go Back",
		typeMessage: "Type your message",
		send: "Send",
		play: "Play",
		//game_menu
		solo: "Single Player",
		multi: "Multiplayer",
		local: "Local",
		duel: "Versus",
		tournament: "Tournament",
		//game_solo
		easy: "Easy",
		medium: "Medium",
		hard: "Hard",
		soloError: "Error starting AI game. Plase try again.",
		//game_local
		localError: "Error starting local game. Plase try again.",
		//game_tournament
		startNextGame: "Start next game",
		createNewTournament: "Create a new Tournament",
		playOff: "PLAYOFF",
		tournamentIsOver: "Tournament is over, winner is ",
		qualified: "Qualified",
		tournamentInput: "Enter tournament name",
		human:"Human",
		tournamentEasy: "AI - Easy",
		tournamentMedium: "AI - Medium",
		tournamentHard: "AI - Hard",
		addPlayer: "+ Add Player",
		createTournament: "Create Tournament",
		loadingNextMatch: "Loading next match...",
		submittingResult: "Submitting match result...",
		aiGameResolved: "Ai game happened at the speed of light",
		maxPlayer: "Maximum of 16 players allowed.",
		enterPlayer: "Enter player",
		tournamentAlphanum: "must only contain alphanumeric characters.",
		tournamentDuplicates: "is duplicated. Please choose unique names.",
		tournamentCreationFailed: "Failed to create tournament. Please try again.",
		TournamentSubmissionFailed: "Failed to submit match result.",
		//game_lobby
		quickMatch: "Quick Match",
		createPrivate: "Create Private Match",
		invitePlayer: " > Invite a Player",
		loading: "Loading...",
		joinRoomError: "Failed to join room. Please try again.",
		//game_utils
		gameOver: "Game Over",
		readyButton: "Start Game",
		waiting: "Waiting...",
		player1: "Player One",
		player2: "Player Two",
		guest: "Guest",
		roomInvite: "Enter the alias of the player you want to invite:",
		invitationSent: "Invitation sent !",
		errorNonExistingRoom: "No game room found with room ID ",
		errorFullRoom: "This game Room is full",
		duplicateRoom: "You are already in Lobby somewhere else",
		gameAborted: "Error: Game was aborted. Please join another game.",
		alreadyInGame: "Error: You are already connected to a game, please finish it or leave it.",
		onGoingGame: "Ongoing game found, do you wish to rejoin?",
		rejoinGame: "Rejoin game",
		concedeGame: "Concede game",
		//Utils
		alphanumError: " can only be made of alphanumerical characters",
		roomName: "Room Name",
	},

	fr: {
		//Login_html
		loginInput: "Identifiant",
		registerTitle: "S'inscrire",
		chooseLogin: "Choisissez un identifiant",
		alias: "Alias",
		chooseAlias: "Choisissez un alias",
		mail: "E-mail",
		enterMail: "Entrez votre e-mail",
		password: "Mot de passe",
		choosePassword: "Choisissez un mot de passe",
		confirmPassword: "Confirmer le mot de passe",
		reenterPassword: "Ressaisissez votre mot de passe",
		registerButton: "S'inscrire",
		alreadyAccount: "Vous avez déjà un compte ?",
		loginLink: "Connectez-vous ici",
		//error and success messages for Login_html
		registerSucceeded: "Succès ! Le profil utilisateur a été créé, vous pouvez maintenant vous connecter.",
		badLanguage: "contient un langage inapproprié",
		loginTaken: "Un utilisateur avec cet identifiant existe déjà",
		aliasTaken: "Un utilisateur avec cet alias existe déjà",
		invalidMail: "Entrez une adresse e-mail valide",
		emailTaken: "Un utilisateur avec cet e-mail existe déjà",
		registerFailed: "Échec de l'inscription, veuillez réessayer plus tard.",
		internalError: "Une erreur s'est produite. Veuillez réessayer plus tard.",
		invalidFormat: "Type de fichier invalide. Seuls les fichiers .jpg et .png sont autorisés.",
		emptyField: "Veuillez remplir ce champ.",
		//login_register
		pwWrongSize: "Le mot de passe doit contenir plus de 12 caractères",
		pwMissingUpper: "Le mot de passe doit contenir au moins une lettre majuscule",
		pwMissingLower: "Le mot de passe doit contenir au moins une lettre minuscule",
		pwMissingNumber: "Le mot de passe doit contenir au moins un chiffre",
		pwMissingSpecial: "Le mot de passe doit contenir au moins un caractère spécial",
		tooLong: "La longueur de l'alias ne peut pas dépasser 10 caractères",
		//login_login
		loginTitle: "Connexion",
		login: "Se connecter",
		enterLogin: "Entrez votre identifiant",
		enterPassword: "Entrez votre mot de passe",
		noAccount: "Vous n'avez pas de compte ?",
		registerLink: "Créez-en un ici",
		twoFactorCode: "Code 2FA",
		enter2FA: "Entrez le code 2FA",
		check2FA: "Vérifier le 2FA",
		//login_login error and success management
		invalidCredential: "Échec de la connexion : Identifiant ou mot de passe invalide",
		enter2FA: "Entrez le code 2FA envoyé à votre e-mail.",
		loginFailed: "Échec de la connexion. Veuillez réessayer.",
		twoFactorFailed: "Échec de la vérification 2FA.",
		//Navbar
		home: "Accueil",
		game: "Jeu",
		leaderboard: "Classement",
		settings: "Paramètres",
		profile: "Profil",
		about: "À propos",
		user: "Utilisateur",
		logout: "Déconnexion",
		personnalData: "Mes informations",
		//Personnal Information
		confirm: "Confirmer",
		cancel: "Annuler",
		language: "Langue",
		//Personnal info Alias change
		aliasChanged: "Succès, l'alias a été changé.",
		IncorrectValue: "Erreur, veuillez entrer une valeur correcte.",
		//Personnal info Mail change
		mailChanged: "Succès, l'e-mail a été changé.",
		oldPassword: "Ancien mot de passe",
		confirmNewPassword: "Confirmer le nouveau mot de passe",
		close: "Fermer",
		newPassword: "Nouveau mot de passe",
		changePassword: "Changer le mot de passe",
		passwordMismatch: "Les mots de passe ne correspondent pas.",
		passwordChanged: "Succès, le mot de passe a été changé.",
		passwordRule: "Votre mot de passe doit blablabla mettre à jour ceci svp", //to update
		profilePicture: "Photo de profil",
		profilePictureHint: "Seuls les fichiers .jpg et .png sont autorisés.",
		errorUploading: "Erreur lors du téléchargement de la photo de profil",
		//profile
		searchByUsername: "Rechercher par nom d'utilisateur",
		profileTitle: "Rechercher un profil",
		searchButton: "Rechercher",
		userNotFound: "Utilisateur non trouvé.",
		status: "Statut",
		rank: "Rang",
		unranked: "Non classé",
		mmr: "MMR",
		winRate: "Taux de victoire",
		wins: "Victoires",
		losses: "Défaites",
		matchHistory: "Historique des matchs :",
		noMatchHistory: "Aucun historique de match trouvé.",
		win: "Victoire",
		loss: "Défaite",
		w: "V",
		l: "D",
		online: "En ligne",
		offline: "Hors ligne",
		ingame: "En jeu",
		friends: "Amis",
		sendMessage: "Envoyer un message",
		requestDuel: "Envoyer une demande de duel",
		addFriend: "Ajouter à la liste d'amis",
		accept: "Accepter",
		cancel: "Annuler",
		block: "Bloquer",
		removeFriend: "Supprimer de la liste d'amis",
		unblock: "Débloquer",
		ban: "ban",
		unban: "unban",
		//leaderboard
		noData: "Aucune donnée disponible",
		//home
		welcome: "Bienvenue",
		currentStats: "Vos statistiques actuelles : ",
		date: "date",
		opponent: "adversaire",
		//FriendList
		friendList: "Liste d'amis",
		noFriends: "Vous n'avez pas d'amis.",
		noFriendRequests: "Vous n'avez aucune demande d'ami en attente.",
		noSentRequests: "Vous n'avez envoyé aucune demande d'ami.",
		noBlocks: "Vous n'avez bloqué aucun utilisateur.",
		blockList: "Liste des utilisateurs bloqués",
		blockUser: "Bloquer un utilisateur",
		addBlock: "Bloquer un nouvel utilisateur",
		addNewFriend: "Ajouter un nouvel ami",
		enterUsername: "Entrez le nom d'utilisateur",
		friendRequests: "Demandes d'amis",
		sentRequests: "Demandes envoyées",
		addBlock: "Ajouter à la liste des bloqués",
		addFriendButton: "Ajouter un ami",
		removeFriend: "Supprimer un ami",
		promptAddBlock: "Entrez le nom d'utilisateur à bloquer",
		promptAddFriend: "Entrez le nom d'utilisateur de l'ami que vous souhaitez ajouter",
		//manage_social
		validationRemovalFirst: "Êtes-vous sûr de vouloir supprimer",
		validationRemovalSecond: "de votre liste d'amis",
		friendRequestSent: "Demande d'ami envoyée",
		validationUnblockFirst: "Êtes-vous sûr de vouloir débloquer",
		validationUnblockSecond: "",
		alreadyFriend: "est déjà votre ami",
		alreadyBlock: "est déjà bloqué",
		notFound: "non trouvé",
		lonelyTest: "... Je veux dire sérieusement, vous ne pouvez pas être si seul... vous voulez un câlin ?",
		chat: "Discussion",
		okSasuke: "... À quel point vous détestez-vous ? mais non, nous ne pouvons pas vous laisser faire cela...",
		userblocked: "a été bloqué",
		colorMode: "Mode couleur",
		blockedByUser: "cet utilisateur vous bloque",
		blockingUser: "vous bloquez cet utilisateur",
		alreadySent: "La demande d'ami a déjà été envoyée.",
		//404
		error404Title: "404",
		error404Message: "Erreur 404 : Page non trouvée",
		//chat
		chatRoomCreationFailed: "Échec de la création de la salle",
		emptyChatRoomName: "Le nom de la salle est vide",
		privateMessages: "Messages privés",
		createOrJoinRoom: "Créer ou rejoindre une salle",
		errorLoadingMessage: "Erreur lors du chargement des messages.",
		hasInvitedYou: "vous a invité à jouer",
		youInvited: "Vous avez envoyé une invitation pour jouer",
		chatRooms: "Salles de discussion",
		privateMessagesWith: "Messages privés avec",
		enterRoomName: "Entrez le nom de la salle",
		tournamentRooms: "Salles de tournoi",
		backButton: "↵ Retour",
		typeMessage: "Tapez votre message",
		send: "Envoyer",
		play: "Jouer",
		//game_menu
		solo: "Solo",
		multi: "Multijoueur",
		local: "Local",
		duel: "Versus",
		tournament: "Tournoi",
		//game_solo
		easy: "Facile",
		medium: "Moyen",
		hard: "Difficile",
		soloError: "Erreur lors du démarrage du jeu contre l'IA. Veuillez réessayer.",
		//game_local
		localError: "Erreur lors du démarrage du jeu local. Veuillez réessayer.",
		//game_tournament
		startNextGame: "Démarrer le prochain jeu",
		createNewTournament: "Créer un nouveau tournoi",
		playOff: "PLAYOFF",
		tournamentIsOver: "Le tournoi est terminé, le gagnant est ",
		qualified: "Qualifié",
		tournamentInput: "Entrez le nom du tournoi",
		human: "Humain",
		tournamentEasy: "IA - Facile",
		tournamentMedium: "IA - Moyenne",
		tournamentHard: "IA - Difficile",
		addPlayer: "+ Ajouter un joueur",
		createTournament: "Créer un tournoi",
		loadingNextMatch: "Chargement du prochain match...",
		submittingResult: "Soumission du résultat du match...",
		aiGameResolved: "Le jeu de l'IA s'est déroulé à la vitesse de la lumière",
		maxPlayer: "Maximum de 16 joueurs autorisés.",
		enterPlayer: "Entrez le joueur",
		tournamentAlphanum: "doit contenir uniquement des caractères alphanumériques.",
		tournamentDuplicates: "est dupliqué. Veuillez choisir des noms uniques.",
		tournamentCreationFailed: "Échec de la création du tournoi. Veuillez réessayer.",
		TournamentSubmissionFailed: "Échec de la soumission du résultat du match.",
		//game_lobby
		quickMatch: "Match rapide",
		createPrivate: "Créer un match privé",
		invitePlayer: " > Inviter un joueur",
		loading: "Chargement...",
		joinRoomError: "Échec de la connexion à la salle. Veuillez réessayer.",
		//game_utils
		gameOver: "Fin de partie",
		readyButton: "Démarrer le jeu",
		waiting: "En attente...",
		player1: "Joueur Un",
		player2: "Joueur Deux",
		guest: "Invité",
		roomInvite: "Entrez l'alias du joueur que vous souhaitez inviter :",
		invitationSent: "Invitation envoyée !",
		errorNonExistingRoom: "Aucune salle de jeux trouvée avec l'ID de salle ",
		errorFullRoom: "Cette salle de jeu est pleine",
		duplicateRoom: "Vous êtes déjà dans le lobby ailleurs",
		gameAborted: "Erreur : Le jeu a été interrompu. Veuillez rejoindre une autre partie.",
		alreadyInGame: "Erreur : Vous êtes déjà connecté à une partie, veuillez la terminer ou la quitter.",
		onGoingGame: "Partie en cours trouvée, souhaitez-vous la rejoindre ?",
		rejoinGame: "Rejoindre la partie",
		concedeGame: "Abandonner la partie",
		//utils
		alphanumError: " ne peut être composé que de caractères alphanumériques",
		roomName: "Le nom de la salle",
	},
	pt: {
		//Login_html
		loginInput: "Entrar",
		registerTitle: "Registrar",
		chooseLogin: "Escolha um login",
		alias: "Apelido",
		chooseAlias: "Escolha um apelido",
		mail: "E-mail",
		enterMail: "Digite seu e-mail",
		password: "Senha",
		choosePassword: "Escolha uma senha",
		confirmPassword: "Confirmar senha",
		reenterPassword: "Digite sua senha novamente",
		registerButton: "Registrar",
		alreadyAccount: "Já tem uma conta?",
		loginLink: "Entre aqui",
		//error and success messages for Login_html
		registerSucceeded: "Sucesso! O perfil do usuário foi criado, agora você pode entrar.",
		badLanguage: "contém linguagem imprópria",
		loginTaken: "Já existe um usuário com este login",
		aliasTaken: "Já existe um usuário com este apelido",
		invalidMail: "Digite um endereço de e-mail válido",
		emailTaken: "Já existe um usuário com este e-mail",
		registerFailed: "Falha no registro, por favor tente novamente mais tarde.",
		internalError: "Ocorreu um erro. Por favor, tente novamente mais tarde.",
		invalidFormat: "Tipo de arquivo inválido. Apenas arquivos .jpg e .png são permitidos.",
		emptyField: "Por favor, preencha este campo.",
		//login_register
		pwWrongSize: "A senha deve ter mais de 12 caracteres",
		pwMissingUpper: "A senha deve conter pelo menos uma letra maiúscula",
		pwMissingLower: "A senha deve conter pelo menos uma letra minúscula",
		pwMissingNumber: "A senha deve conter pelo menos um número",
		pwMissingSpecial: "A senha deve conter pelo menos um caractere especial",
		tooLong: "O comprimento do alias não pode exceder 10 caracteres",
		//login_login
		loginTitle: "Entrar",
		login: "Entrar",
		enterLogin: "Digite seu login",
		enterPassword: "Digite sua senha",
		noAccount: "Não tem uma conta?",
		registerLink: "Crie uma aqui",
		twoFactorCode: "Código 2FA",
		enter2FA: "Digite o código 2FA",
		check2FA: "Verificar 2FA",
		//login_login error and success management
		invalidCredential: "Falha no login: Login ou senha inválidos",
		enter2FA: "Digite o código 2FA enviado para seu e-mail.",
		loginFailed: "Falha no login. Por favor, tente novamente.",
		twoFactorFailed: "Falha na verificação do 2FA.",
		//Navbar
		home: "Início",
		game: "Jogo",
		leaderboard: "Ranking",
		settings: "Configurações",
		profile: "Perfil",
		about: "Sobre",
		user: "Usuário",
		logout: "Sair",
		personnalData: "Minhas informações",
		//Personnal Information
		confirm: "Confirmar",
		cancel: "Cancelar",
		language: "Linguagem",
		//Personnal info Alias change
		aliasChanged: "Sucesso, o apelido foi alterado.",
		IncorrectValue: "Erro, por favor insira um valor correto.",
		//Personnal info Mail change
		mailChanged: "Sucesso, o e-mail foi alterado.",
		oldPassword: "Senha antiga",
		confirmNewPassword: "Confirme a nova senha",
		close: "Fechar",
		newPassword: "Nova senha",
		changePassword: "Alterar senha",
		passwordMismatch: "As senhas não coincidem.",
		passwordChanged: "Sucesso, a senha foi alterada.",
		passwordRule: "Sua senha deve blablabla atualizar isso por favor", //to update
		profilePicture: "Foto de perfil",
		profilePictureHint: "Apenas arquivos .jpg e .png são permitidos.",
		errorUploading: "Erro ao enviar a foto de perfil",
		//profile
		searchByUsername: "Pesquisar por nome de usuário",
		profileTitle: "Pesquisar Perfil",
		searchButton: "Pesquisar",
		userNotFound: "Usuário não encontrado.",
		status: "Status",
		rank: "Classificação",
		unranked: "Não classificado",
		mmr: "MMR",
		winRate: "Taxa de vitórias",
		wins: "Vitórias",
		losses: "Derrotas",
		matchHistory: "Histórico de partidas:",
		noMatchHistory: "Nenhum histórico de partidas encontrado.",
		win: "Vitória",
		loss: "Derrota",
		w: "V",
		l: "D",
		online: "Online",
		offline: "Offline",
		ingame: "Em jogo",
		friends: "Amigos",
		sendMessage: "Enviar mensagem",
		requestDuel: "Enviar pedido de duelo",
		addFriend: "Adicionar à lista de amigos",
		accept: "Aceitar",
		cancel: "Cancelar",
		block: "Bloquear",
		removeFriend: "Remover da lista de amigos",
		unblock: "Desbloquear",
		ban: "ban",
		unban: "unban",
		//leaderboard
		noData: "Sem dados disponíveis",
		//home
		welcome: "Bem-vindo",
		currentStats: "Suas estatísticas atuais: ",
		date: "data",
		opponent: "oponente",
		//FriendList
		friendList: "Lista de amigos",
		noFriends: "Você não tem amigos.",
		noFriendRequests: "Você não tem pedidos de amizade pendentes.",
		noSentRequests: "Você não enviou nenhum pedido de amizade.",
		noBlocks: "Você não bloqueou nenhum usuário.",
		blockList: "Lista de bloqueados",
		blockUser: "Bloquear Usuário",
		addBlock: "Bloquear um novo usuário",
		addNewFriend: "Adicionar um novo amigo",
		enterUsername: "Digite o nome de usuário",
		friendRequests: "Pedidos de amizade",
		sentRequests: "Pedidos enviados",
		addBlock: "Adicionar à lista de bloqueados",
		addFriendButton: "Adicionar amigo",
		removeFriend: "Remover amigo",
		promptAddBlock: "Digite o nome de usuário para bloquear",
		promptAddFriend: "Digite o nome de usuário do amigo que você deseja adicionar",
		//manage_social
		validationRemovalFirst: "Tem certeza de que deseja remover",
		validationRemovalSecond: "da sua lista de amigos",
		friendRequestSent: "Pedido de amizade enviado",
		validationUnblockFirst: "Tem certeza de que deseja desbloquear",
		validationUnblockSecond: "",
		alreadyFriend: "já é seu amigo",
		alreadyBlock: "já está bloqueado",
		notFound: "não encontrado",
		lonelyTest: "... Sério, você não pode estar tão sozinho assim... quer um abraço?",
		chat: "Chat",
		okSasuke: "... Até que ponto você se odeia? mas não, não podemos deixar você fazer isso...",
		userblocked: "foi bloqueado",
		colorMode: "Modo de cor",
		blockedByUser: "este usuário está bloqueando você",
		blockingUser: "você está bloqueando este usuário",
		alreadySent: "Pedido de amizade já foi enviado.",
		//404
		error404Title: "404",
		error404Message: "Erro 404: Página não encontrada",
		//chat
		chatRoomCreationFailed: "Falha ao criar a sala",
		emptyChatRoomName: "O nome da sala está vazio",
		privateMessages: "Mensagens privadas",
		createOrJoinRoom: "Criar ou entrar em sala",
		errorLoadingMessage: "Erro ao carregar mensagens.",
		hasInvitedYou: "convidou você para jogar",
		youInvited: "Você enviou um convite para jogar",
		chatRooms: "Salas de chat",
		privateMessagesWith: "Mensagens privadas com",
		enterRoomName: "Digite o nome da sala",
		tournamentRooms: "Salas de torneio",
		backButton: "↵ Voltar",
		typeMessage: "Digite sua mensagem",
		send: "Enviar",
		play: "Jogar",
		//game_menu
		solo: "Solo",
		multi: "Multijogador",
		local: "Local",
		duel: "Versus",
		tournament: "Torneio",
		//game_solo
		easy: "Fácil",
		medium: "Médio",
		hard: "Difícil",
		soloError: "Erro ao iniciar o jogo contra IA. Por favor, tente novamente.",
		//game_local
		localError: "Erro ao iniciar o jogo local. Por favor, tente novamente.",
		//game_tournament
		startNextGame: "Iniciar próximo jogo",
		createNewTournament: "Criar novo torneio",
		playOff: "PLAYOFF",
		tournamentIsOver: "O torneio acabou, o vencedor é ",
		qualified: "Qualificado",
		tournamentInput: "Digite o nome do torneio",
		human: "Humano",
		tournamentEasy: "IA - Fácil",
		tournamentMedium: "IA - Médio",
		tournamentHard: "IA - Difícil",
		addPlayer: "+ Adicionar jogador",
		createTournament: "Criar torneio",
		loadingNextMatch: "Carregando próxima partida...",
		submittingResult: "Enviando resultado da partida...",
		aiGameResolved: "O jogo da IA aconteceu à velocidade da luz",
		maxPlayer: "Máximo de 16 jogadores permitidos.",
		enterPlayer: "Digite o jogador",
		tournamentAlphanum: "deve conter apenas caracteres alfanuméricos.",
		tournamentDuplicates: "está duplicado. Por favor, escolha nomes únicos.",
		tournamentCreationFailed: "Falha ao criar torneio. Por favor, tente novamente.",
		TournamentSubmissionFailed: "Falha ao enviar resultado da partida.",
		//game_lobby
		quickMatch: "Partida rápida",
		createPrivate: "Criar partida privada",
		invitePlayer: " > Convidar jogador",
		loading: "Carregando...",
		joinRoomError: "Falha ao entrar na sala. Por favor, tente novamente.",
		//game_utils
		gameOver: "Fim de jogo",
		readyButton: "Iniciar jogo",
		waiting: "Esperando...",
		player1: "Jogador Um",
		player2: "Jogador Dois",
		guest: "Convidado",
		roomInvite: "Digite o apelido do jogador que você deseja convidar:",
		invitationSent: "Convite enviado!",
		errorNonExistingRoom: "Nenhuma sala de jogos encontrada com o ID da sala",
		errorFullRoom: "Esta sala de jogos está cheia",
		duplicateRoom: "Você já está no Lobby em outro lugar",
		gameAborted: "Erro: O jogo foi interrompido. Por favor, entre em outro jogo.",
		alreadyInGame: "Erro: Você já está conectado a um jogo, por favor termine ou saia dele.",
		onGoingGame: "Jogo em andamento encontrado, deseja entrar novamente?",
		rejoinGame: "Entrar novamente no jogo",
		concedeGame: "Desistir do jogo",
		//utils
		alphanumError: " só pode ser composto por caracteres alfanuméricos",
		roomName: "Lo nome da sala",
	},
}
