name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test-build:
    runs-on:  ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build and Test with Makefile
        run: make all

      - name: Stop and Remove Containers
        if: always()
        run: make clean
